# Generated by Django 5.1.2 on 2024-10-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
