# Generated by Django 5.1.2 on 2024-10-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_cartitem_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='days',
        ),
    ]
