# Generated by Django 5.1.2 on 2024-10-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_remove_car_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
