# Generated by Django 5.1.2 on 2024-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_car_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
