# Generated by Django 5.1.2 on 2024-10-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('ended', 'ended'), ('cancelled', 'Cancelled')], default='started', max_length=20),
        ),
    ]
