# Generated by Django 5.1.2 on 2024-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_orderitem_end_date_orderitem_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
