# Generated by Django 5.1.2 on 2024-12-25 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_profile_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Enter a valid 12-digit Aadhar number')]),
        ),
    ]
